
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const GET_ARTICLES = 'GET_ARTICLES';
export const UPLOAD_VID = 'UPLOAD_VID';
export const UPLOAD_IMG = 'UPLOAD_IMG';
export const UPDATE_CONSTANT = 'UPDATE_CONSTANT';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const CHECK_COMMENT = 'CHECK_COMMENT';
export const CHECK_MESSAGE = 'CHECK_MESSAGE';
export const CHECK_FEEDBACK = 'CHECK_FEEDBACK';
export const CHECK_CHAT = 'CHECK_CHAT';
export const CHECK_CONTENTRATING = 'CHECK_CONTENTRATING';
export const CHECK_ACCRATING = 'CHECK_ACCRATING';

